### ISSUE TITLE
Questions on grammars used in XML/EXI processing

### ISSUE THREAD

**Issue by shaohu** [EXIficient/exificient.js#2]
Hi guys,

In this library, during the process of encoding/decoding between XML and EXI files, the grammars are always required. In your README file, there is an instruction about how to generated the grammars file from schema file. While when I using this library, some questions arose:  
1. I know that the schema file can be used for compressing the file size during encoding XML file into EXI file. However, in your "main" project of EXficient - [exificient-java](https://github.com/EXIficient/exificient), using the schema file is _optional_, which means I can choose not using the schemas. But here the grammars are _required_ during encoding and decoding. I'm not quite understand why.  
2. Following the question 1, when I tried to generate a grammars file from schema file by using [exificient-grammars](https://github.com/EXIficient/exificient-grammars), I noticed a significant increase in file size. e.g. a 2KB .xsd file can result in a 5MB grammars file. I think the increasement of file size would counteract the benefits of file compressing by using grammars, especially under the web environment.
3. When I tested my data set on the [demo page](http://exificient.github.io/javascript/demo/processXML.html), there arose some exceptions. I'm not sure they are bugs or just because this library is still under developing and many data types are not supported yet.

I've attached the sample data for question 2 and 3 here: [sample_data.zip](https://github.com/EXIficient/exificient.js/files/255949/sample_data.zip).

After all, you guys did a good job!

Thanks
Hu Shao

**Comment by danielpeintner** [comment]
Hi,

# w.r.t.your question 1

EXI format supports schema-less and schema-informed processing.

The EXIficient.js library currently supports only schema-informed processing.
We plan to implement schema-less EXI streams also.

#  w.r.t.your question 2

Given that we do not have an XML schema processor in JS we thought converting the EXI grammars into JSON makes sense. I still think it does but the chosen format might not be the best w.r.t. size. We need to investigate further.
The size of the grammars depend a lot on the chosen XML schema constructs too.

The grammars can be compressed with the EXI-for-JSON format first. This should make the file much smaller.

#  w.r.t.your question 3

I need to look into that. At the moment we do not support all schema-informed types also.
That might cause issues too.
The project is still on going..

Hope this helps,

-- Daniel

**Comment by danielpeintner** [comment]
Hi,

i have been looking at your XML example. This schema includes another schema which again includes others et cetera. That said... the XML schema isn't as simple as you thought I think.

Moreover, while the EXI spec allows for deviant data as in your example the current exificient.js implementation does not. I did change the XML instance slightly to make it valid (see attached issue2.xml).

In the meanwhile I also updates some code portions so that your example works.

Hope this helps.

-- Daniel


[issue2.zip](https://github.com/EXIficient/exificient.js/files/261415/issue2.zip)

**Comment by shaohu** [comment]
Hi Daniel,

Thanks a lot for your efforts, It helps a lot!!!
I will spend some time to get more familiar with this library.

Best wishes,
Hu

**Comment by danielpeintner** [comment]
Work has still to be done to support schema-less EXI streams. Planned for release v0.0.3
