### ISSUE TITLE
Exificient.js demo - Incorrect boolean value on decode

### ISSUE THREAD

**Issue by BEllis** [EXIficient/exificient.js#9]
On the demo site,

http://exificient.github.io/javascript/demo/processJSON.html

if you encode and decode the sample, any false boolean values will be changed from false to true.

**Comment by danielpeintner** [comment]
Thanks for the provided fix.

In the meanwhile I encountered another issue with tsc tranformation see https://github.com/EXIficient/exificient.js/issues/13
